jobs:
  BuildAndTest:
    name: Build and Test on JDK ${{ matrix.java_version }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - continue-on-error: true
      name: Install JDK ${{ matrix.java_version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Install Android SDK
      uses: malinskiy/action-android/install-sdk@release/0.1.0
    - continue-on-error: true
      name: Build project
      run: ./gradlew assemble
    - continue-on-error: true
      name: Run tests
      run: ./gradlew :OpenKeychain:test
    - continue-on-error: true
      if: failure()
      name: Archive UnitTest report
      uses: actions/upload-artifact@v2
      with:
        name: UnitTest-report
        path: ${{ github.workspace }}/**/build/reports/tests/testDebugUnitTest
    strategy:
      matrix:
        java_version:
        - 17
name: CI
on:
  repository_dispatch:
    types: trigger-ga___android-ci.yml
